### ISSUE TITLE
chore: move the controller-specific logic from the models to the controllers

### ISSUE THREAD

**Issue by lilsweetcaligula** [OpenPromisesProject/api#133]
Right now, we have code in our models that looks like this:

https://github.com/OpenPromisesProject/op-serverless-api/blob/master/functions/models/contributor.ts#L74
```
if (_.isEmpty(contributor)) {
  return { status: 404, message: 'Invalid Contributor' };
}
```

However, the model should not build the response object, - it is the duty of the controller. Instead, we should either return `null` or throw an error.

**Comment by lilsweetcaligula** [comment]
@nazreen What do you think about this?

**Comment by nazreen** [comment]
makes sense. I personally will be prioritising below-mentioned issue. if you can pick this up, please do.

as I was pushing my commits I realised that the files don't have the best organisation which will impede any future development
some model files have been modularised so that each method is in one file. some have not.

I also think that we might benefit from doing a feature based structure rather than a type based structure. As in, all files relating to promises in one folder (the api, model, etc) rather than sitting in various folders. This opinion I am still considering.

**Comment by lilsweetcaligula** [comment]
@nazreen

> I also think that we might benefit from doing a feature based structure rather than a type based structure.

This is a very good suggestion. From experience, the `feature-based` structure is superior to the `type-based` one, and is so much easier to expand upon. The `type-based` one only works for small codebases, that have a very limited scope.

> some model files have been modularised so that each method is in one file. some have not.

I found the best way to structure a module is by putting everything in the single `.js` file, and defining all functions inside a single object or classdef:
```
const FooUtils = {
  async fooThis(what) {},

  async fooThat(what) {}
}

module.exports = FooUtils
```

I found that the one I advertised in the past (function per file, interface defined in `index.js`) is an anti-pattern.
